### ISSUE TITLE
Numbering scheme?

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries-incubator/shell-extras#2]
A) Do lessons need to be numbered?

B) If so, is there a need for some sort of intentional numbering scheme, or can we just do first-come, first-served?

**Comment by gvwilson** [comment]
Please number, since there's usually at least a partial order among 
topics.  Beyond that, FCFS.

**Comment by gdevenyi** [comment]
Since this is an extras repo, FCFS seems fine.
