### ISSUE TITLE
Ask the community for help: exercises

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries-incubator/shell-extras#52]
A bunch of instructors from the University of Oslo (@heereman and myself, probably one more) are considering submitting a proposal to teach this material at CarpentryConnect Manchester in June this year. We feel there is a lot of useful material here that would be useful for those that use the unix shell regularly. However, the big gap is exercises. Would the maintainers (are that @gdevenyi and/or @ChristinaLK?) willing to put out a call to the community for creating sets of exercises between now and June?

**Comment by gcapes** [comment]
@swcarpentry/shell-maintainers

**Comment by gdevenyi** [comment]
Absolutely we can put out the call, I'm not not sure where we should do that :)

Perhaps a blog post would be in order to make the call...

**Comment by heereman** [comment]
A blogpost would certainly be fine. We can spread that using other channels like Twitter, Slack a.o. What would be the right place to publish this blogpost?

**Comment by lexnederbragt** [comment]
Closed as we are now past the event for which we were thinking of using the material.
