### ISSUE TITLE
Add website to repo description

### ISSUE THREAD

**Issue by gcapes** [carpentries-incubator/shell-extras#53]
Normally the SWC lessons have the website shown at the top of the repo right after the repo description. I don't have the ability to change this as a maintainer. Perhaps @ErinBecker can add this?

http://swcarpentry.github.io/shell-extras/

Thanks

**Comment by fmichonneau** [comment]
thanks for pointing this out @gcapes. I have added it.

**Comment by gcapes** [comment]
Great, thanks!
