### ISSUE TITLE
04-directory-structure (Teach Noble's directory structure)

### ISSUE THREAD

**Issue by gvwilson** [carpentries-incubator/shell-extras#6]
There should be a lesson explaining the directory structure laid out in Noble's paper (1) and implemented here (2).
1. http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1000424
2. https://github.com/Reproducible-Science-Curriculum/rr-init

**Comment by vuw-ecs-kevin** [comment]
I was looking for more content to pull into my 
https://github.com/vuw-ecs-kevin/shell-extras/tree/import-intermediate-shell-content
branch, and came across this discussion thread, given that 04-directory-structure
is still completely deviod of content.

For me, "the directory structure laid out in Noble's paper" and the "implentation" 
referred to have liltle to do with the way that shells work, and lie more in the "higher
level recommendations around project management practice" camp.

(Oh, and why are graphs stored in a directory called "figures",  so as to distinguish
 them from "diagrams, images, and other non-graph graphics", which are, themsleves, 
 stored in  "pictures" but not "graphics" ?
 I could hear, to use the nomenclature of publications, "figures" as opposed to "tables" 
  but "figures" as opposed to "pictures" doesn't really seem all that disticnt ?
 Surely the set of graphs, if you believe them not to be graphics, that is, as opposed
  to the set of non-graphs, might as well be placed into a directory called "graphs",
  as that's all that will be in there?
 But. I digress.)

In terrms of "directory structure", as viewed from the perspective of introduicing
the shell, the material I was expecting to find in here appears to be covered in 
the shell-novice lesson's episodes, "Navigating Files and Directories" and 
"Working With Files and Directories" .

So, I can't see that this episode (rather, a Teach Noble's directory structure
episode) should be in a "Shell Extras" lesson, and with "the Teach the shell's 
directory structure" being covered in the Shell Novice lesson's episodes, would
suggest that it goes.
