### ISSUE TITLE
Add this lesson to community-lessons page

### ISSUE THREAD

**Issue by ErinBecker** [carpentries-incubator/shell-extras#62]
This lesson was previously hosted in the SWC GH organization, but not listed on the SWC lessons page, so not visible to many who were searching for more advanced shell resources. To increase visibility and community discussion and use of lessons outside of The Carpentries core curricula, we've migrated this resource to the Incubator. 

@fmichonneau has [updated the lesson template](https://github.com/carpentries/carpentries-theme/pull/1) to enable support of Incubator lessons:

This update:
- Creates a top-of-page banner to indicate that this lesson is in the incubator (and not a core Carpentries lesson). This banner is in addition to the existing "lesson life cycle" banner that appears on some official Carpentries lessons (for example [the geospatial lessons](https://datacarpentry.org/organization-geospatial/)) to indicate whether lessons are pre-alpha, alpha, beta, or stable. 

- Changes the license information to make it clear the copyright is not held by The Carpentries or any of its lesson programs. 

- Replaces The Carpentries (or SWC/DC/LC) logo in the upper left hand corner of the template with The Carpentries Incubator logo. 

@fmichonneau has put together a PR to bring these template updates into this repo. Once this has been done, your lesson will appear on a "Community Contributed Lessons" page on The Carpentries website! 

Looking forward to posting your lesson publically and getting the word out about this awesome resource!

**Comment by gdevenyi** [comment]
Fixed by #61
