### ISSUE TITLE
Shell extras setup files missing

### ISSUE THREAD

**Issue by dcharmey** [carpentries-incubator/shell-extras#63]
Hi,

Could someone upload back the setup files for **carpentries-incubator/shell-extras** lesson?

Thanks a lot!

**Comment by gdevenyi** [comment]
Hi @dcharmey I'm not sure what you're referring to, can you be a bit more specific? Thanks!

**Comment by dcharmey** [comment]
Hello @gdevenyi,

I am looking for the files that are missing here : [https://carpentries-incubator.github.io/shell-extras/setup.html] or here : [https://swcarpentry.github.io/shell-extras/]

It would be great to have access to those files to follow the shell extra lesson properly.

Let me know if you still have them,

Thanks a lot !

**Comment by gcapes** [comment]
I think that 'Download files required for the lesson' is a default part of the template on the setup page. I don't think there are any files to download for this lesson.

However, the course does require an account on a remote machine for episode 2.

**Comment by gdevenyi** [comment]
There have never been any Setup files for this lesson as far as I can tell. These episodes are mostly standalone, and assume you have successfully setup and completed the shell-novice lesson. As such, we could probably specify that completion of shell-novice is the setup required for this lesson.

> I think that 'Download files required for the lesson' is a default part of the template on the setup page.
I'm not sure what you're referring to @gcapes I don't see that on any template or mentioned by @dcharmey

**Comment by dcharmey** [comment]
Hi, 

I did not realise that the file cohort2010.txt was just an example, and that the .bashrc file was part of my home directory. Sorry about that..

Thank you for your time!

**Comment by gdevenyi** [comment]
No problem, thanks for reaching out!
