### ISSUE TITLE
Job control episode: link broken

### ISSUE THREAD

**Issue by aaklee** [carpentries-incubator/shell-extras#76]
The link to the definition for job control in the introduction seems to be broken. The link points to: https://carpentries-incubator.github.io/shell-extras/06-job-control/%7B%20page.root%20%7D%7D/reference/#job-control. It looks like it wants to link out to the reference page here: https://carpentries-incubator.github.io/shell-extras/reference.html#key-points

**Comment by kynan** [comment]
This is a simple typo :) Fixed by #77
